PREFIX :<http://www.ontotext.com/connectors/retrieval#>
PREFIX inst:<http://www.ontotext.com/connectors/retrieval/instance#>
INSERT DATA {
  inst:qa_dataset :createConnector '''
{
  "fields": [
    {
      "fieldName": "text",
      "propertyChain": [
        "https://www.statnett.no/Talk2PowerSystem/qa#nl_question"
      ]
    }
  ],
  "types": [
    "https://www.statnett.no/Talk2PowerSystem/qa#Question"
  ],
  "retrievalUrl": "http://retrieval-plugin:8080/OpenAIDocument",
  "retrievalBearerToken": "DUMMY"
  "bulkUpdateBatchSize": 50
}
''' .
}
