PREFIX cims: <http://iec.ch/TC57/1999/rdf-schema-extensions-19990926#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX cimex: <https://rawgit2.com/statnett/Talk2PowerSystem/main/demo1/cimex/>
PREFIX cim: <http://iec.ch/TC57/2013/CIM-schema-cim16#>
PREFIX entose: <http://entsoe.eu/CIM/SchemaExtension/3/1#>
PREFIX entose2: <http://entsoe.eu/CIM/SchemaExtension/3/2#>
PREFIX uml: <http://iec.ch/TC57/NonStandard/UML#>
CONSTRUCT {
    ?x ?p ?o
} FROM onto:explicit WHERE
{
    {
        SELECT DISTINCT ?x {
            {
                [] ?x []
            } UNION {
                [] a ?x
            }
        }
    } UNION {
        ?x rdfs:isDefinedBy cimex:
    } UNION {
        ?enumeration cims:stereotype uml:enumeration.
        ?x a ?enumeration.
        [] ?y ?x.
    }
    ?x ?p ?o
}
