CONSTRUCT {
    ?x ?p ?o
} FROM <http://www.ontotext.com/explicit> WHERE
{
    {
        SELECT DISTINCT ?x {
            {
                [] ?x []
            } UNION {
                [] a ?x
            }
        }
    } UNION {
        ?x <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <https://rawgit2.com/statnett/Talk2PowerSystem/main/demo1/cimex/>
    } UNION {
        ?enumeration <http://iec.ch/TC57/1999/rdf-schema-extensions-19990926#stereotype> <http://iec.ch/TC57/NonStandard/UML#enumeration>.
        ?x a ?enumeration.
        [] ?y ?x.
    }
    ?x ?p ?o
}
