PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?uri ?name ?date ?version {
    ?uri a owl:Ontology.
    OPTIONAL {
        ?uri rdfs:label ?name
    }
    OPTIONAL {
        ?uri dct:title ?name
    }
    OPTIONAL {
        ?uri owl:versionInfo ?version
    }
    OPTIONAL {
        ?uri dct:modified ?date
    }
}
ORDER BY ?name
