apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "t2ps-chatbot-llm.fullname.config.properties" . }}
  namespace: {{ include "t2ps-chatbot-llm.namespace" . }}
  labels:
    {{- include "t2ps-chatbot-llm.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  REDIS_HOST: {{ include "redis.host" . }}
  {{- if .Values.configuration.properties }}
    {{- range $key, $val := .Values.configuration.properties -}}
      {{- if ne $val nil }}
        {{- $key | nindent 2 }}: {{ tpl ($val | toString) $ }}
      {{- end }}
    {{- end -}}
  {{- end -}}
