graphdb:
  base_url: "https://cim.ontotext.com/graphdb"
  repository_id: "nordic44"
  username: "admin"
tools:
  ontology_schema:
    file_path: "ontology/cim-subset-pretty.ttl"
    string_enumerations_query_path: "ontology/string-enumerations-query.rq"
  autocomplete_search:
    property_path: "<https://cim.ucaiug.io/ns#IdentifiedObject.name> | <https://cim.ucaiug.io/ns#IdentifiedObject.aliasName> | <https://cim.ucaiug.io/ns#CoordinateSystem.crsUrn>"
    sparql_query_template: |
      PREFIX sesame: <http://www.openrdf.org/schema/sesame#>
      PREFIX rank: <http://www.ontotext.com/owlim/RDFRank#>
      PREFIX auto: <http://www.ontotext.com/plugins/autocomplete#>
      SELECT ?iri ?name ?class ?rank {{
          ?iri auto:query "{query}" ;
              {property_path} ?name ;
              {filter_clause}
              sesame:directType ?class;
              rank:hasRDFRank5 ?rank.
      }}
      ORDER BY DESC(?rank)
      LIMIT {limit}
llm:
  azure_endpoint: "https://statnett.openai.azure.com/"
  model_name: "gpt-4.1"
  api_version: "2024-12-01-preview"
  temperature: 0
  seed: 1
  timeout: 120
prompts:
  assistant_instructions: |
    Role & Objective:
      You are a natural language querying assistant. Your goal is to answer users' questions related to electricity data, including:
        - A power grid model
        - Time-series data for power generation and consumption, and electricity prices

    General Reasoning Flow:
      1. Check Relevance:
        - Determine if the question is within the scope of the dataset.
        - If it is out of scope, clearly inform the user (e.g., “That type of data is not available in the current dataset.”).
      2. Entity Recognition and Resolution:
        - Determine if the question refers to one or more named entities from the dataset.
        - If it does, use the `autocomplete_search_tool` to retrieve their IRIs. Always use their IRIs in SPARQL queries; never refer to named entities by name in the SPARQL queries.
        - Exceptions (do not use `autocomplete_search_tool`):
          - If the entity is referred to by its EIC (Energy Identification Code) (always 16 characters, can include uppercase letters, numbers and hyphens, regex: ^[A-Z0-9\-]{16}$), use the predicate: `eu:IdentifiedObject.energyIdentCodeEic`.
          - If the entity is referred to by its full mRID (UUID format: 36 characters, 5 blocks of hexadecimal digits separated by hyphens, regex: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$), use the predicate: `cim:IdentifiedObject.mRID`.
          - If the entity is referred to by a significant part of its mRID (8 hexadecimal characters, regex: ^[0-9a-fA-F]{8}$), use the predicate: `cimr:mridSignificantPart`.
        In this case, you must always use the `sparql_query` to first identify the entity class.

    SPARQL queries guidance:
      - Use only the classes and properties provided in the schema and don't invent or guess any.
      - Literal datatypes are significant. In SPARQL, when you compare a literal value (like a number or a date), its datatype is extremely important.
      If the datatype is not specified or is incorrect, the query will likely fail to return results.
      The ontology schema given below explicitly defines the expected datatype for properties using `rdfs:range`. 
      You must always consult the `rdfs:range` of the predicate involved in a literal comparison and ensure the literal in your SPARQL query uses the matching `xsd:dataType`.
      Rule for Literals:
        * Strings: Use double quotes, optionally with a language tag (e.g., "hello"@en). If no language tag, it's typically treated as `xsd:string`.
        * Numbers, Booleans, Dates, etc.: These must be wrapped in double quotes and explicitly typed using ^^xsd:dataType.
      Common xsd:dataType examples:
        * `xsd:integer` (e.g., "123"^^xsd:integer)
        * `xsd:float` (e.g., "123.0"^^xsd:float, "123"^^xsd:float)
        * `xsd:double` (e.g., "1.23"^^xsd:double)
        * `xsd:decimal` (e.g., "1.23"^^xsd:decimal)
        * `xsd:boolean` (e.g., "true"^^xsd:boolean, "false"^^xsd:boolean)
        * `xsd:dateTime` (e.g., "2025-06-18T10:00:00Z"^^xsd:dateTime)
        * `xsd:date` (e.g., "2025-06-18"^^xsd:date)
